### ISSUE TITLE
Add git submodule issue for hugo to the docs

### ISSUE THREAD

**Issue by momack2** [FleekHQ/fleek-docs#12]
I ran directly into the issue described in https://blog.fleek.co/posts/go-with-hugo-and-fleek - however it took me a while to find this solution because I was looking at the docs instead of your thorough and useful blog post. Can we merge this content back into docs.fleek.co - either on the Site Deploy or Build Configurations pages? A decent stop gap would be a callout linking directly to the blog itself for anyone having issues with Hugo.

**Comment by momack2** [comment]
Also, an important step to remind folks to do at home with hugo templates is to go into their config.toml and set relativeURLs = "true" such that they actually work when loaded from different roots. 
![image](https://user-images.githubusercontent.com/618519/80324559-39ca2b80-87e6-11ea-9e98-0c42ce5a232f.png)

**Comment by Blockchainbrett** [comment]
Hey @momack2 !

Thanks so much for opening the issue. We will definitely add it to the tech docs. 

@SamueleA Maybe you have a good idea where to best put it. I think at least referencing the article is good.

**Comment by SamueleA** [comment]
I added a section `Tips By Framework` with a Hugo section in the docs to explain the relativeUrls configuration.

I believe the problem must with the git subdomule must be something else. We automatically update the git submodules even without the git subdomule command.

I also removed the section about git subdomule command since it will cause unnecessary confusion.
